<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31" started-at="2019-04-17T09:29:11Z" finished-at="2019-04-17T09:29:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31" started-at="2019-04-17T09:29:11Z" finished-at="2019-04-17T09:29:11Z">
      <class name="com.ofs.maven.ToDoListTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.ofs.maven.ToDoListTest@42eca56e]" name="setup" is-config="true" duration-ms="15" started-at="2019-04-17T09:29:11Z" finished-at="2019-04-17T09:29:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testCreatePositive(com.ofs.maven.model.ToDo, java.lang.Throwable)[pri:0, instance:com.ofs.maven.ToDoListTest@42eca56e]" name="testCreatePositive" duration-ms="16" started-at="2019-04-17T09:29:11Z" data-provider="testCreatePositive" finished-at="2019-04-17T09:29:11Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: testCreatePositive([Parameter{index=0, type=com.ofs.maven.model.ToDo, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Throwable, declaredAnnotations=[]}])
Arguments: [(com.ofs.maven.model.ToDo) com.ofs.maven.model.ToDo@517cd4b,(com.ofs.maven.model.ToDo) com.ofs.maven.model.ToDo@6cc7b4de]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: testCreatePositive([Parameter{index=0, type=com.ofs.maven.model.ToDo, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Throwable, declaredAnnotations=[]}])
Arguments: [(com.ofs.maven.model.ToDo) com.ofs.maven.model.ToDo@517cd4b,(com.ofs.maven.model.ToDo) com.ofs.maven.model.ToDo@6cc7b4de]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:982)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePositive -->
      </class> <!-- com.ofs.maven.ToDoListTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
